"""Deterministic Markdown rendering for GlacierWatch's structured outputs.

Never calls a model - same discipline as bidwright/rendering.py and
claimclarity/rendering.py: the files written to disk (and the "what needs
attention this week" summary) always reflect the validated structured data
exactly, not an LLM's retelling of it.
"""
from __future__ import annotations

from glacierwatch.models import (
    CommunityAlertBulletin,
    CurrentConditions,
    InspectionSchedule,
    PriorityLevel,
    SiteTrend,
    TrendClassification,
    WatchlistReport,
    WatchSite,
)

DISCLAIMER = (
    "**This is a decision-support triage tool, not a prediction system.** It combines "
    "published, cited hazard assessments with live weather and seismic data using "
    "documented trigger thresholds, to help prioritize limited monitoring and inspection "
    "resources. It does not and cannot predict whether, when, or where an avalanche or "
    "glacial lake outburst flood will occur. On-site glaciological and geotechnical "
    "assessment by qualified experts is required for any operational decision, including "
    "evacuation."
)


def _bullets(items: list[str]) -> str:
    if not items:
        return "_None._"
    return "\n".join(f"- {item}" for item in items)


def render_site_profile_md(site: WatchSite) -> str:
    aka = f" (also known as {', '.join(site.also_known_as)})" if site.also_known_as else ""
    return f"""### {site.name}{aka}
**Location:** {site.district}, {site.state} — {site.river_basin} basin ({site.latitude}, {site.longitude}), {site.elevation_m} m elevation
**Status:** {site.status.replace('_', ' ')}
**Documented classification:** {site.static_risk_classification}

**Documented risk factors:**
{_bullets(site.static_risk_factors)}

**Downstream exposure:** {site.downstream_exposure or "_not documented_"}

**Sources:** {'; '.join(site.sources) if site.sources else "_not documented_"}
"""


def render_conditions_md(conditions: CurrentConditions) -> str:
    precip_lines = "\n".join(
        f"- {r.date}: {r.precipitation_mm:.1f} mm ({r.category})" for r in conditions.precipitation_recent_days
    ) or "_No precipitation data available._"
    quake_lines = "\n".join(
        f"- M{e.magnitude:.1f}, {e.distance_km:.0f} km away, {e.place} ({e.time})"
        for e in conditions.nearby_seismic_events
    ) or "_No seismic events matching the search criteria._"

    return f"""#### Conditions as of {conditions.as_of}

**Precipitation (recent days, including today so far):**
{precip_lines}

Max daily precipitation: {conditions.max_daily_precipitation_mm:.1f} mm
{"⚠️ Heavy rainfall threshold met or exceeded" if conditions.heavy_rainfall_flag else "No heavy-rainfall threshold crossed"}

**Nearby seismic activity:**
{quake_lines}

_Weather source: {conditions.weather_source_note or "not recorded"}_
_Seismic source: {conditions.seismic_source_note or "not recorded"}_
"""


def render_watchlist_report_md(report: WatchlistReport, trends: list[SiteTrend] | None = None) -> str:
    """The one file a disaster management officer should actually read.
    Generated by plain code, not the model, so the priority ranking is
    guaranteed to reflect the structured SiteRiskBriefs exactly.

    `trends` (from record_run_history_and_detect_trends) is optional so
    every existing caller/test that only has a WatchlistReport keeps working
    unchanged. When given, sites with a rising trend that are NOT already at
    priority level this week get one deterministic early-warning line here -
    the whole point of tracking trend is to reach the official reading this
    file, not just a separate trend_report.md nobody opens. This never
    claims what a rising trend portends, only that it's happening; see
    trend_report.md for every site's full trend detail.
    """
    priority_order = {PriorityLevel.PRIORITY: 0, PriorityLevel.ELEVATED: 1, PriorityLevel.ROUTINE: 2}
    ordered = sorted(report.briefs, key=lambda b: priority_order.get(b.priority_level, 99))

    icon = {
        PriorityLevel.PRIORITY: "🔴 PRIORITY",
        PriorityLevel.ELEVATED: "🟡 ELEVATED",
        PriorityLevel.ROUTINE: "🟢 ROUTINE",
    }

    lines = ["# GlacierWatch Weekly Watchlist", "", DISCLAIMER, "", f"**Summary:** {report.overall_summary}", ""]

    if trends:
        briefs_by_id = {b.site_id: b for b in report.briefs}
        rising_not_yet_priority = [
            t
            for t in trends
            if t.trend == TrendClassification.RISING
            and briefs_by_id.get(t.site_id) is not None
            and briefs_by_id[t.site_id].priority_level != PriorityLevel.PRIORITY
        ]
        if rising_not_yet_priority:
            names = ", ".join(t.site_name for t in rising_not_yet_priority)
            lines.append(
                f"**Trend early-warning:** {len(rising_not_yet_priority)} site(s) show a rising trend across "
                f"recent runs but are not yet at priority level this week - recommend closer monitoring: "
                f"{names}. See trend_report.md for details."
            )
            lines.append("")

    for brief in ordered:
        lines.append(f"## {icon.get(brief.priority_level, brief.priority_level.value.upper())} — {brief.site_name}")
        lines.append(f"**Rationale:** {brief.rationale}")
        if brief.active_triggers:
            lines.append("**Active triggers this week:**")
            lines.extend(f"- {t}" for t in brief.active_triggers)
        lines.append(f"**Recommended action:** {brief.recommended_action}")
        lines.append("")

    return "\n".join(lines)


def render_community_alert_md(bulletin: CommunityAlertBulletin) -> str:
    """One village-committee-facing bulletin for one priority-level site.
    Same discipline as render_watchlist_report_md: generated by plain code
    from the validated CommunityAlertBulletin, disclaimer always included."""
    settlement_lines = "\n".join(
        f"- **{s.name}** — ~{s.distance_km:.0f} km downstream, {s.population_band}"
        + (f" ({s.notes})" if s.notes else "")
        for s in bulletin.settlements_to_notify
    ) or "_No downstream settlement data available yet for this site - see glacierwatch/data/downstream_exposure.json._"

    return f"""# Community Alert Bulletin — {bulletin.site_name}

**Priority level this week:** {bulletin.priority_level.value.upper()}

{DISCLAIMER}

## Situation, in plain terms
{bulletin.situation_summary}

## Settlements to notify
{settlement_lines}

## What your committee should do
{_bullets(bulletin.recommended_actions)}

## Alert text (English)
{bulletin.alert_text_en}

## Alert text (local language)
{bulletin.alert_text_local}
"""


def render_community_alerts_index_md(bulletins: list[CommunityAlertBulletin]) -> str:
    """Index of every community alert bulletin drafted this run. Always
    written, even when the list is empty, so a reader can tell "zero
    bulletins this week" apart from "the pipeline didn't run"."""
    if not bulletins:
        return (
            "# Community Alert Bulletins Index\n\n"
            "No sites were at priority level this week - no community alert bulletins were drafted.\n"
        )

    lines = [
        "# Community Alert Bulletins Index",
        "",
        f"{len(bulletins)} site(s) at priority level this week have a community alert bulletin below.",
        "",
    ]
    for bulletin in bulletins:
        lines.append(
            f"- [{bulletin.site_name}](community_alert_{bulletin.site_id}.md) — "
            f"{len(bulletin.settlements_to_notify)} settlement(s) to notify"
        )
    lines.append("")
    return "\n".join(lines)


def render_trend_report_md(trends: list[SiteTrend]) -> str:
    """Every assessed active_watch site's run-over-run trend classification.
    Always written, even when there's nothing trending or every site has
    insufficient_history - a reader should be able to tell "checked, nothing
    rising" apart from "this step never ran", same discipline as
    render_community_alerts_index_md.

    This describes the trend of already-OBSERVED conditions across past
    runs, generated by plain code from validated SiteTrend objects (see
    glacierwatch/tools/history.py:classify_trend) - it is never a forecast
    of what happens next, and never claims what a rising trend portends.
    """
    lines = [
        "# GlacierWatch Run History & Trend Early-Warning Report",
        "",
        DISCLAIMER,
        "",
        "**This report describes the trend of already-observed conditions across past runs - it is not a "
        "forecast.** A rising trend means recent-day rainfall and/or nearby seismic activity have been "
        "increasing run over run; it does not mean an avalanche or glacial lake outburst flood is more "
        "likely, and a flat or insufficient-history classification does not mean a site is safe.",
        "",
    ]

    if not trends:
        lines.append(
            "No sites had current-run conditions recorded this run - there is nothing to classify a trend for."
        )
        return "\n".join(lines)

    rising = [t for t in trends if t.trend == TrendClassification.RISING]
    lines.append(f"**{len(rising)} of {len(trends)} site(s) show a rising trend this run.**")
    lines.append("")

    icon = {
        TrendClassification.RISING: "📈 RISING",
        TrendClassification.FALLING: "📉 FALLING",
        TrendClassification.FLAT: "➡️ FLAT",
        TrendClassification.INSUFFICIENT_HISTORY: "❓ INSUFFICIENT HISTORY",
    }
    trend_order = {
        TrendClassification.RISING: 0,
        TrendClassification.FALLING: 1,
        TrendClassification.FLAT: 2,
        TrendClassification.INSUFFICIENT_HISTORY: 3,
    }
    for t in sorted(trends, key=lambda t: trend_order.get(t.trend, 99)):
        lines.append(f"## {icon.get(t.trend, t.trend.value.upper())} — {t.site_name}")
        lines.append(f"Based on {t.runs_considered} recorded run(s), this run included.")
        lines.append(t.explanation)
        lines.append("")

    return "\n".join(lines)


def render_inspection_schedule_md(schedule: InspectionSchedule) -> str:
    """The field team's weekly work plan - an ordered stop list a team lead
    can literally follow out the door, generated by plain code from the
    validated InspectionSchedule (glacierwatch/tools/scheduler.py) so the
    order and rationale shown here always match exactly what was computed,
    never a retelling. Always written, even when zero stops were scheduled -
    same discipline as render_community_alerts_index_md and
    render_trend_report_md: a reader should be able to tell "checked,
    nothing to schedule" apart from "this step never ran."
    """
    icon = {
        PriorityLevel.PRIORITY: "🔴 PRIORITY",
        PriorityLevel.ELEVATED: "🟡 ELEVATED",
        PriorityLevel.ROUTINE: "🟢 ROUTINE",
    }

    lines = ["# GlacierWatch Field Inspection Schedule", "", DISCLAIMER, "", f"**Summary:** {schedule.summary}", ""]

    if not schedule.stops:
        lines.append("_No stops to show this week - see summary above._")
        return "\n".join(lines)

    lines.append(
        "**Suggested visiting order below is a computed starting point, not a mandate** - a greedy "
        "nearest-neighbor route over straight-line distance between sites, not real mountain road travel "
        "time. Always defer to the field team's own local road knowledge for the actual driving order."
    )
    lines.append("")

    for i, stop in enumerate(schedule.stops, start=1):
        lines.append(f"## Stop {i}: {icon.get(stop.priority_level, stop.priority_level.value.upper())} — {stop.site_name}")
        lines.append(f"**Location:** {stop.latitude}, {stop.longitude}")
        lines.append(f"**Why visit:** {stop.why_visit}")
        lines.append("")

    return "\n".join(lines)
