"""Deterministic Markdown rendering for GlacierWatch's structured outputs.

Never calls a model - same discipline as bidwright/rendering.py and
claimclarity/rendering.py: the files written to disk (and the "what needs
attention this week" summary) always reflect the validated structured data
exactly, not an LLM's retelling of it.
"""
from __future__ import annotations

from glacierwatch.models import CommunityAlertBulletin, CurrentConditions, PriorityLevel, WatchlistReport, WatchSite

DISCLAIMER = (
    "**This is a decision-support triage tool, not a prediction system.** It combines "
    "published, cited hazard assessments with live weather and seismic data using "
    "documented trigger thresholds, to help prioritize limited monitoring and inspection "
    "resources. It does not and cannot predict whether, when, or where an avalanche or "
    "glacial lake outburst flood will occur. On-site glaciological and geotechnical "
    "assessment by qualified experts is required for any operational decision, including "
    "evacuation."
)


def _bullets(items: list[str]) -> str:
    if not items:
        return "_None._"
    return "\n".join(f"- {item}" for item in items)


def render_site_profile_md(site: WatchSite) -> str:
    aka = f" (also known as {', '.join(site.also_known_as)})" if site.also_known_as else ""
    return f"""### {site.name}{aka}
**Location:** {site.district}, {site.state} — {site.river_basin} basin ({site.latitude}, {site.longitude}), {site.elevation_m} m elevation
**Status:** {site.status.replace('_', ' ')}
**Documented classification:** {site.static_risk_classification}

**Documented risk factors:**
{_bullets(site.static_risk_factors)}

**Downstream exposure:** {site.downstream_exposure or "_not documented_"}

**Sources:** {'; '.join(site.sources) if site.sources else "_not documented_"}
"""


def render_conditions_md(conditions: CurrentConditions) -> str:
    precip_lines = "\n".join(
        f"- {r.date}: {r.precipitation_mm:.1f} mm ({r.category})" for r in conditions.precipitation_recent_days
    ) or "_No precipitation data available._"
    quake_lines = "\n".join(
        f"- M{e.magnitude:.1f}, {e.distance_km:.0f} km away, {e.place} ({e.time})"
        for e in conditions.nearby_seismic_events
    ) or "_No seismic events matching the search criteria._"

    return f"""#### Conditions as of {conditions.as_of}

**Precipitation (recent days, including today so far):**
{precip_lines}

Max daily precipitation: {conditions.max_daily_precipitation_mm:.1f} mm
{"⚠️ Heavy rainfall threshold met or exceeded" if conditions.heavy_rainfall_flag else "No heavy-rainfall threshold crossed"}

**Nearby seismic activity:**
{quake_lines}

_Weather source: {conditions.weather_source_note or "not recorded"}_
_Seismic source: {conditions.seismic_source_note or "not recorded"}_
"""


def render_watchlist_report_md(report: WatchlistReport) -> str:
    """The one file a disaster management officer should actually read.
    Generated by plain code, not the model, so the priority ranking is
    guaranteed to reflect the structured SiteRiskBriefs exactly."""
    priority_order = {PriorityLevel.PRIORITY: 0, PriorityLevel.ELEVATED: 1, PriorityLevel.ROUTINE: 2}
    ordered = sorted(report.briefs, key=lambda b: priority_order.get(b.priority_level, 99))

    icon = {
        PriorityLevel.PRIORITY: "🔴 PRIORITY",
        PriorityLevel.ELEVATED: "🟡 ELEVATED",
        PriorityLevel.ROUTINE: "🟢 ROUTINE",
    }

    lines = ["# GlacierWatch Weekly Watchlist", "", DISCLAIMER, "", f"**Summary:** {report.overall_summary}", ""]
    for brief in ordered:
        lines.append(f"## {icon.get(brief.priority_level, brief.priority_level.value.upper())} — {brief.site_name}")
        lines.append(f"**Rationale:** {brief.rationale}")
        if brief.active_triggers:
            lines.append("**Active triggers this week:**")
            lines.extend(f"- {t}" for t in brief.active_triggers)
        lines.append(f"**Recommended action:** {brief.recommended_action}")
        lines.append("")

    return "\n".join(lines)


def render_community_alert_md(bulletin: CommunityAlertBulletin) -> str:
    """One village-committee-facing bulletin for one priority-level site.
    Same discipline as render_watchlist_report_md: generated by plain code
    from the validated CommunityAlertBulletin, disclaimer always included."""
    settlement_lines = "\n".join(
        f"- **{s.name}** — ~{s.distance_km:.0f} km downstream, {s.population_band}"
        + (f" ({s.notes})" if s.notes else "")
        for s in bulletin.settlements_to_notify
    ) or "_No downstream settlement data available yet for this site - see glacierwatch/data/downstream_exposure.json._"

    return f"""# Community Alert Bulletin — {bulletin.site_name}

**Priority level this week:** {bulletin.priority_level.value.upper()}

{DISCLAIMER}

## Situation, in plain terms
{bulletin.situation_summary}

## Settlements to notify
{settlement_lines}

## What your committee should do
{_bullets(bulletin.recommended_actions)}

## Alert text (English)
{bulletin.alert_text_en}

## Alert text (local language)
{bulletin.alert_text_local}
"""


def render_community_alerts_index_md(bulletins: list[CommunityAlertBulletin]) -> str:
    """Index of every community alert bulletin drafted this run. Always
    written, even when the list is empty, so a reader can tell "zero
    bulletins this week" apart from "the pipeline didn't run"."""
    if not bulletins:
        return (
            "# Community Alert Bulletins Index\n\n"
            "No sites were at priority level this week - no community alert bulletins were drafted.\n"
        )

    lines = [
        "# Community Alert Bulletins Index",
        "",
        f"{len(bulletins)} site(s) at priority level this week have a community alert bulletin below.",
        "",
    ]
    for bulletin in bulletins:
        lines.append(
            f"- [{bulletin.site_name}](community_alert_{bulletin.site_id}.md) — "
            f"{len(bulletin.settlements_to_notify)} settlement(s) to notify"
        )
    lines.append("")
    return "\n".join(lines)
